### ISSUE TITLE
Failed to detect 

### ISSUE THREAD

**Issue by nenodias** [pingo-io/pingo-py#111]
Opening Arduino Serial port /dev/ttyUSB0 

Please wait while Arduino is being detected. This can take up to 30 seconds ...
Board Auto Discovery Failed!, Shutting Down

It's a chinese Arduino Board.

**Comment by Vido** [comment]
@nenodias ,

Have you uploaded the StandardFirmata Sketch into to your Arduino?
Pingo can't  control your Arduino without the Firmata protocol.

Thanks.

**Comment by nenodias** [comment]
Thanks for reply.
