### ISSUE TITLE
Is there any preview for getting Pingo in Python 3.5

### ISSUE THREAD

**Issue by vmesel** [pingo-io/pingo-py#112]
Can we expect pingo for python 3.5?

**Comment by rafaelhenrique** [comment]
do you have any strategy to migrate!? @vmesel

**Comment by vmesel** [comment]
nope, not really @rafaelhenrique !
Vido was helping me with this, probably Ill need to go to Garoa to figure out how we can do things compatible with the Python 3

**Comment by scls19fr** [comment]
You might have a look at

https://github.com/pingo-io/pingo-py/issues/100
https://github.com/pingo-io/pingo-py/issues/45

I really think a first step before a Python 3 version of Pingo is to accept Enum PR
https://github.com/pingo-io/pingo-py/pull/109

After this I could help
see https://github.com/pingo-io/pingo-py/pull/109
