### ISSUE TITLE
PyBoard. @mantonelli do you need help?

### ISSUE THREAD

**Issue by Vido** [pingo-io/pingo-py#48]
Hi @mantonelli,

We noticed that you started working on PyBoard.
But you seem you to have stopped.

Send us and email on pingo-io@googlegroups.com
We will be glad to help you.

Thanks.

**Comment by scls19fr** [comment]
According https://micropython.org/ https://github.com/micropython/micropython/ and https://github.com/micropython/pyboard
it's working on Python 3 so we should probably first need to have a Python 2/3 support.
