### ISSUE TITLE
Support controlling servo motors

### ISSUE THREAD

**Issue by felipesanches** [pingo-io/pingo-py#53]
I felt this specific need while I was planning to control a set of servos for a remake of the Golly Ghost arcade.

**Comment by Vido** [comment]
* Erin and Gabriel asked about this.
* Marcos from Telefonica asked too.
* Oda wants to build a PayPal paid foosball

So folks this feature is top priority.

**Comment by Vido** [comment]
Last Sunday, I was working on the "Nativity scene" software.
And I used a I2C PWM driver http://www.adafruit.com/datasheets/PCA9685.pdf
Although it is a "LED controller optimized for LCD Red/Green/Blue/Amber (RGBA) color backlighting applications", you can drive servos.

It provides a 12bits (4096 states) duty cycle. Here is the math:
```
At 50Hz, we have a 20ms period.

0º is 0.5ms -> 20ms/0.5ms = 40
4096 / 40 = 102.4 ~ 103

90º is 1.5ms -> 20ms/1.5ms = 13.3
4096 / 13.3 = 307.9 ~ 308

180º is 2.5ms -> 20ms/2.5ms = 8
4096 / 8 = 512
```
Yes, this trick works. Any board with a setable PWM frequency, with at least 40 states, will work

So far:
* There are some libraries that support servos: eg. PyMata (https://github.com/MrYsLab/PyMata/blob/master/examples/servo/servo_demo.py)
* Most of Pingo's drivers have no support.

Should Servo be a pingo.parts or should it be a Board.mode?
Well, if it's implementation hangs upon each Board, we can't have it as pure pingo.parts.
If a code is Board specific, than it should be within it's own Board driver.
