### ISSUE TITLE
The GPIOs of Galileo2 only have location, they not have gpio_id

### ISSUE THREAD

**Issue by gfth4x07** [pingo-io/pingo-py#80]

**Comment by Vido** [comment]
Yes and no.

They are multiplexed pins. MRAA creates a abstration, so we control only at a logical level (not the GPIO it self)

This is a schematics about how it works:

Credits: http://www.malinov.com/Home/sergey-s-blog/intelgalileo-programminggpiofromlinux
![galileo_linux_io](https://cloud.githubusercontent.com/assets/956388/8458289/b0e66240-1fec-11e5-8131-3ab8a3b4c845.png)
