### ISSUE TITLE
New to pingo, can't get it working !

### ISSUE THREAD

**Issue by hary66** [pingo-io/pingo-py#91]
Hi everyone.

As I said I'm new to pingo.
I'm trying to use pingo with different card, but I can't get anyone of them working.

Currently, with the Arduino UNO I get this message  :
########
harold@localhost:~/Documents/python$ python essaiPingo

Python Version 2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)]

PyMata version 2.10  Copyright(C) 2013-15 Alan Yorinks    All rights reserved.

Opening Arduino Serial port /dev/ttyACM0 

Please wait while Arduino is being detected. This can take up to 30 seconds ...
Board Auto Discovery Failed!, Shutting Down
Traceback (most recent call last):
  File "essaiPingo", line 8, in <module>
    led = b.pins[13]
  File "/usr/lib64/python2.7/UserDict.py", line 22, in __getitem__
    return self.__class__.__missing__(self, key)
  File "/home/harold/pingo/pingo/util.py", line 61, in __missing__
    return self[self.normalize(key)]
  File "/usr/lib64/python2.7/UserDict.py", line 22, in __getitem__
    return self.__class__.__missing__(self, key)
  File "/home/harold/pingo/pingo/util.py", line 60, in __missing__
    raise KeyError(key)
KeyError: '13'
########

My Arduino code is : 
######
#include <Firmata.h>
#include <Boards.h>
void setup()
{}
void loop()
{}
########

The "Tx" led on the UNO is blinking while attempting detection

I'm using Ardino IDE 1.0.6 to upload to the UNO.
Any advice ?

**Comment by Vido** [comment]
Hi @hary66 ,

Thanks for using pingo.

We have a mail-list, where the main contributors adresses this kind of problem:
https://groups.google.com/forum/#!forum/pingo-io
I recomend you to ask your question there. We consider Github's Issue tracker a bug/feature backlog.

Have you uploaded the StandardFirmata Sketch into to your Arduino?
Pingo can't talk with an Arduino without the Firmata protocol.

Sorry, I guess we haven't put enough emphasis on the documentation.

**Comment by hary66** [comment]
Sorry to come back, but it seems I'm not authorized to do anything on
https://groups.google.com/forum/#!forum/pingo-io !

I can't open new question or answer any !  I guess I need  to be accepted by any kind of moderator ????
